#!/usr/bin/env python3

#
# Copyright 2010-2012,2014-2015 Ettus Research LLC
# Copyright 2021 Ettus Research, a National Instruments Company
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

#This utility allows for the viewing of dat files generated by the OARER architecture.
#Example Use: python3 readDatFile.py -folder="/mnt/md1/" -base-rx="rx_00" -start-point=0 -end-point=16000 -pps=200 -fs="250000000" 
# See util.py for command line argument explanations or use python3 readDatFile.py -h

import sys
import logging as log
from plots import *
from util import *
from usrpDat import *

def main():
    args = parse_args()
    if args.verbose:
        log.basicConfig(level=log.DEBUG)
    if args.filename: 
        log.info("File {} selected.".format(args.filename))
        filesize = os.path.getsize(args.filename)
        iq_data = get_iq_object(args.filename, args.format, filesize)
        #TODO: Finish for single File
    elif args.folder:
        iq_data_dict, complex_dict = read_in_folders(args.folder,"/mnt/md0/")

    alignment, avg_alignment = calculate_ptp_alignment_all(iq_data_dict, args.base_rx, args.pps)
    create_plot_directories("temp")
    for data in alignment:
        plot_ptp_average(iq_data_dict[data], iq_data_dict[args.base_rx], avg_alignment, "temp", args.start_point, args.end_point, args.pps)
        plot_ptp_alignment(iq_data_dict[data], iq_data_dict[args.base_rx], alignment, "temp", args.start_point, args.end_point)
    for data in iq_data_dict:
        if data != args.base_rx:
            plot_samps(iq_data_dict[data], iq_data_dict[args.base_rx], "temp",  args.start_point, args.end_point)
            
if __name__ == "__main__":
    sys.exit(not main())